Deploy the Telegraf-based connectors at TTS
lsst-sqre/phalanx pull request #3717
Opened 2024-09-24 20:16 UTC by afausti

2024-09-24 20:35 UTC, mareuter requested changes
Somethings to fix up here otherwise it will mess up TTS.

2024-09-24 20:35 UTC, mareuter commented on applications/sasquatch/values-tucson-teststand.yaml
> +    lsstcam:
LSSTCam is not available on TTS. Remove it.

2024-09-24 20:35 UTC, mareuter commented on applications/sasquatch/values-tucson-teststand.yaml
> -    calsys:
The calibrations systems are still in Tucson. This needs to be restored.

2024-09-24 20:35 UTC, mareuter commented on applications/sasquatch/values-tucson-teststand.yaml
> -    comcam:
ComCam is on TTS. This needs to be restored/added.

2024-09-24 20:35 UTC, mareuter commented on applications/sasquatch/values-tucson-teststand.yaml
> -        [ ".*ATMonochromator", ".*ATWhiteLight", ".*CBP", ".*Electrometer", ".*FiberSpectrograph", ".*LEDProjector", ".*LinearStage", ".*MTReflector", ".*TunableLaser" ]
ATMonochromator and ATWhiteLight can be removed.

2024-09-24 21:01 UTC, afausti commented
Argh, sorry about that, I naively copied the BTS configuration here.

2024-09-25 22:47 UTC, mareuter approved these changes
Diffs are a bit weird, but I think all the fixes are there.

2024-09-25 22:49 UTC, merged